name: Deploy Website
on:
  push:
    branches: [main]
  # Allow manual triggering
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy src to Learn Subdomain
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./src/
          server-dir: /learn.glitchitsystem.com/public_html/core-concepts/
          protocol: ftp
          log-level: standard
          dangerous-clean-slate: true
          timeout: 30000
          port: 21

      - name: Deploy src to Main Site
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./src/
          server-dir: /glitchitsystem.com/public_html/core-concepts/
          protocol: ftp
          log-level: standard
          dangerous-clean-slate: true
          timeout: 30000
          port: 21
